// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : marfin
Date           : Tue Jul 16 16:30:07 2013
Host           : Linux lxbuild170.cern.ch 2.6.18-308.1.1.el5 #1 SMP Wed Mar 7 19:25:07 CET 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/user/marfin/CMSSW_5_3_3/src/Analysis/HbbMSSMAnalysis/test/Analysis2012/tmva_test_v7/train_mva_standalone
Training events: 2100000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "N,N-1" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
SamplingTraining: "False" [The training sample is sampled]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Et2byEt1                      Et2byEt1                      Et2byEt1                      Et2byEt1                      F                                 'F'    [0.0329739265144,0.999999880791]
Et3byEt1                      Et3byEt1                      Et3byEt1                      Et3byEt1                      F                                 'F'    [0.00723528303206,0.998612701893]
Et3byEt2                      Et3byEt2                      Et3byEt2                      Et3byEt2                      F                                 'F'    [0.00730751501396,1]
djet1jet2pt                   djet1jet2pt                   djet1jet2pt                   djet1jet2pt                   F                                 'F'    [0.00363541697152,0.996129393578]
dphijet1jet2                  dphijet1jet2                  dphijet1jet2                  dphijet1jet2                  F                                 'F'    [4.74463449791e-05,3.14159250259]
dphijet2jet3                  dphijet2jet3                  dphijet2jet3                  dphijet2jet3                  F                                 'F'    [4.78156437111e-07,3.1415913105]
dptjet1jet2                   dptjet1jet2                   dptjet1jet2                   dptjet1jet2                   F                                 'F'    [4.39227072491e-08,0.911039710045]
dptjet1jet3                   dptjet1jet3                   dptjet1jet3                   dptjet1jet3                   F                                 'F'    [0.000330226437654,0.930747449398]
maxdijetmass                  maxdijetmass                  maxdijetmass                  maxdijetmass                  F                                 'F'    [0.226021185517,0.996123611927]
mindijetmass                  mindijetmass                  mindijetmass                  mindijetmass                  F                                 'F'    [0.00305365934037,0.583633124828]
thetajet1_boost12             thetajet1_boost12             thetajet1_boost12             thetajet1_boost12             F                                 'F'    [0.0137960426509,3.13912081718]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Et2byEt1", "Et3byEt1", "Et3byEt2", "djet1jet2pt", "dphijet1jet2", "dphijet2jet3", "dptjet1jet2", "dptjet1jet3", "maxdijetmass", "mindijetmass", "thetajet1_boost12" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[11][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][11];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 11; fWeights[2] = new double[11]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.38665957258696;
   fWeightMatrix0to1[1][0] = 3.22398989968545;
   fWeightMatrix0to1[2][0] = -0.304848643876848;
   fWeightMatrix0to1[3][0] = 1.82216015507721;
   fWeightMatrix0to1[4][0] = -1.7833513251792;
   fWeightMatrix0to1[5][0] = 2.91069933371869;
   fWeightMatrix0to1[6][0] = -1.47886306591766;
   fWeightMatrix0to1[7][0] = 5.38839599343319;
   fWeightMatrix0to1[8][0] = -4.39907026513781;
   fWeightMatrix0to1[9][0] = -2.12738910819212;
   fWeightMatrix0to1[10][0] = -1.31765350706666;
   fWeightMatrix0to1[0][1] = 1.00587537693958;
   fWeightMatrix0to1[1][1] = -0.855347440903456;
   fWeightMatrix0to1[2][1] = 0.447738886525229;
   fWeightMatrix0to1[3][1] = 1.10938972831336;
   fWeightMatrix0to1[4][1] = -0.590588196159179;
   fWeightMatrix0to1[5][1] = -2.9601682805345;
   fWeightMatrix0to1[6][1] = 2.16351391881686;
   fWeightMatrix0to1[7][1] = 2.48741682536031;
   fWeightMatrix0to1[8][1] = 1.25528353282137;
   fWeightMatrix0to1[9][1] = -0.0274202779557188;
   fWeightMatrix0to1[10][1] = -0.417494282589035;
   fWeightMatrix0to1[0][2] = 3.11396784719512;
   fWeightMatrix0to1[1][2] = -0.181078800796532;
   fWeightMatrix0to1[2][2] = -3.41854266927979;
   fWeightMatrix0to1[3][2] = -2.40059641260348;
   fWeightMatrix0to1[4][2] = 3.02067157564079;
   fWeightMatrix0to1[5][2] = 0.96880170749565;
   fWeightMatrix0to1[6][2] = -2.10405009299323;
   fWeightMatrix0to1[7][2] = -6.46516815607984;
   fWeightMatrix0to1[8][2] = 2.59184184192373;
   fWeightMatrix0to1[9][2] = 0.889823211364492;
   fWeightMatrix0to1[10][2] = -1.29806902332428;
   fWeightMatrix0to1[0][3] = -5.54473791263555;
   fWeightMatrix0to1[1][3] = 0.618288775417317;
   fWeightMatrix0to1[2][3] = 3.60471425200934;
   fWeightMatrix0to1[3][3] = -3.25812240080671;
   fWeightMatrix0to1[4][3] = 0.395447805179033;
   fWeightMatrix0to1[5][3] = -4.50933879952682;
   fWeightMatrix0to1[6][3] = -0.0376612785527351;
   fWeightMatrix0to1[7][3] = 5.93922924296181;
   fWeightMatrix0to1[8][3] = -2.90420774269695;
   fWeightMatrix0to1[9][3] = 5.48517496823119;
   fWeightMatrix0to1[10][3] = 1.53583115704939;
   fWeightMatrix0to1[0][4] = 3.35634256082863;
   fWeightMatrix0to1[1][4] = -1.56345323013242;
   fWeightMatrix0to1[2][4] = -3.51729639476153;
   fWeightMatrix0to1[3][4] = -2.62438186328384;
   fWeightMatrix0to1[4][4] = 5.43281321307528;
   fWeightMatrix0to1[5][4] = 6.91413635720561;
   fWeightMatrix0to1[6][4] = 0.285982477094087;
   fWeightMatrix0to1[7][4] = 7.90216718614912;
   fWeightMatrix0to1[8][4] = -5.60627964659847;
   fWeightMatrix0to1[9][4] = -0.938639720133066;
   fWeightMatrix0to1[10][4] = -0.777066398291399;
   fWeightMatrix0to1[0][5] = -1.09751964130015;
   fWeightMatrix0to1[1][5] = -0.228102789355371;
   fWeightMatrix0to1[2][5] = -1.62859416471218;
   fWeightMatrix0to1[3][5] = 1.45014831706842;
   fWeightMatrix0to1[4][5] = 0.456014857134274;
   fWeightMatrix0to1[5][5] = -4.97036397586187;
   fWeightMatrix0to1[6][5] = 0.154175434174265;
   fWeightMatrix0to1[7][5] = -5.36081300395536;
   fWeightMatrix0to1[8][5] = 4.2245422943755;
   fWeightMatrix0to1[9][5] = 0.0192427305413102;
   fWeightMatrix0to1[10][5] = -1.5461486306562;
   fWeightMatrix0to1[0][6] = 1.5841065793088;
   fWeightMatrix0to1[1][6] = -2.4046299549549;
   fWeightMatrix0to1[2][6] = 4.72886396764153;
   fWeightMatrix0to1[3][6] = 1.56623662411185;
   fWeightMatrix0to1[4][6] = -0.837084145290796;
   fWeightMatrix0to1[5][6] = -2.65837743698343;
   fWeightMatrix0to1[6][6] = 1.93553360754258;
   fWeightMatrix0to1[7][6] = 1.48126705917233;
   fWeightMatrix0to1[8][6] = 2.2168236705266;
   fWeightMatrix0to1[9][6] = -0.526987207202743;
   fWeightMatrix0to1[10][6] = -1.37340497875109;
   fWeightMatrix0to1[0][7] = 0.253084909941957;
   fWeightMatrix0to1[1][7] = 0.36850547237699;
   fWeightMatrix0to1[2][7] = -2.05314154089405;
   fWeightMatrix0to1[3][7] = 4.07471250189864;
   fWeightMatrix0to1[4][7] = 4.0542118494971;
   fWeightMatrix0to1[5][7] = 1.63407671735075;
   fWeightMatrix0to1[6][7] = -0.214135748555439;
   fWeightMatrix0to1[7][7] = 0.563711698016258;
   fWeightMatrix0to1[8][7] = -1.34342213775568;
   fWeightMatrix0to1[9][7] = 1.15876105516437;
   fWeightMatrix0to1[10][7] = -0.78825313491063;
   fWeightMatrix0to1[0][8] = -2.73262121146935;
   fWeightMatrix0to1[1][8] = -0.722464365335509;
   fWeightMatrix0to1[2][8] = -0.195825709576238;
   fWeightMatrix0to1[3][8] = -2.14490603439878;
   fWeightMatrix0to1[4][8] = 4.30370069382404;
   fWeightMatrix0to1[5][8] = -1.59700852999855;
   fWeightMatrix0to1[6][8] = -1.07273841279166;
   fWeightMatrix0to1[7][8] = 1.67415372983255;
   fWeightMatrix0to1[8][8] = -4.34976104853935;
   fWeightMatrix0to1[9][8] = -1.50407104953897;
   fWeightMatrix0to1[10][8] = -1.78787733487035;
   fWeightMatrix0to1[0][9] = 1.56695522009881;
   fWeightMatrix0to1[1][9] = -0.991535973023738;
   fWeightMatrix0to1[2][9] = -2.59781601026471;
   fWeightMatrix0to1[3][9] = -2.00349886984219;
   fWeightMatrix0to1[4][9] = 1.17189012200176;
   fWeightMatrix0to1[5][9] = -1.71642773374459;
   fWeightMatrix0to1[6][9] = 0.398984890874512;
   fWeightMatrix0to1[7][9] = -4.4204538461003;
   fWeightMatrix0to1[8][9] = 2.4417571233439;
   fWeightMatrix0to1[9][9] = -1.6411547720432;
   fWeightMatrix0to1[10][9] = -0.382780013779993;
   fWeightMatrix0to1[0][10] = -3.07230201147929;
   fWeightMatrix0to1[1][10] = 2.56313592767277;
   fWeightMatrix0to1[2][10] = -1.08467235872065;
   fWeightMatrix0to1[3][10] = -0.708819512752683;
   fWeightMatrix0to1[4][10] = -4.60171173760288;
   fWeightMatrix0to1[5][10] = 3.31135126100671;
   fWeightMatrix0to1[6][10] = 0.576418741881966;
   fWeightMatrix0to1[7][10] = -2.19680442234369;
   fWeightMatrix0to1[8][10] = 5.77556672815779;
   fWeightMatrix0to1[9][10] = -0.946622775200119;
   fWeightMatrix0to1[10][10] = -1.30280790843318;
   fWeightMatrix0to1[0][11] = -0.0781491908830808;
   fWeightMatrix0to1[1][11] = 1.66345824680296;
   fWeightMatrix0to1[2][11] = 4.90609524596636;
   fWeightMatrix0to1[3][11] = -3.08149673943111;
   fWeightMatrix0to1[4][11] = 0.945931089780009;
   fWeightMatrix0to1[5][11] = -3.59251981999088;
   fWeightMatrix0to1[6][11] = -1.72183705750331;
   fWeightMatrix0to1[7][11] = -4.21665585993778;
   fWeightMatrix0to1[8][11] = 3.57572010569683;
   fWeightMatrix0to1[9][11] = -1.96344454448878;
   fWeightMatrix0to1[10][11] = -3.32590131474404;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 4.23460226134912;
   fWeightMatrix1to2[1][0] = -1.18006098954199;
   fWeightMatrix1to2[2][0] = 0.0253325622089195;
   fWeightMatrix1to2[3][0] = 0.115888604973079;
   fWeightMatrix1to2[4][0] = 10.6665910199117;
   fWeightMatrix1to2[5][0] = -8.00135531473205;
   fWeightMatrix1to2[6][0] = 1.82900308523469;
   fWeightMatrix1to2[7][0] = 4.75560166213854;
   fWeightMatrix1to2[8][0] = 5.5678457624825;
   fWeightMatrix1to2[9][0] = 0.443749150578614;
   fWeightMatrix1to2[0][1] = -4.85294228042714;
   fWeightMatrix1to2[1][1] = -1.99301303649045;
   fWeightMatrix1to2[2][1] = -0.865120179999673;
   fWeightMatrix1to2[3][1] = 1.30387051173639;
   fWeightMatrix1to2[4][1] = 2.18542048165331;
   fWeightMatrix1to2[5][1] = -1.96157049297897;
   fWeightMatrix1to2[6][1] = -0.358030194749073;
   fWeightMatrix1to2[7][1] = 1.52422833930851;
   fWeightMatrix1to2[8][1] = -0.967313812514892;
   fWeightMatrix1to2[9][1] = -0.0678589107757497;
   fWeightMatrix1to2[0][2] = 4.84972400833148;
   fWeightMatrix1to2[1][2] = -0.0712152578078268;
   fWeightMatrix1to2[2][2] = -1.40341170953476;
   fWeightMatrix1to2[3][2] = 0.479371900672561;
   fWeightMatrix1to2[4][2] = 6.84752013689055;
   fWeightMatrix1to2[5][2] = 2.87430088536679;
   fWeightMatrix1to2[6][2] = 1.05668308602428;
   fWeightMatrix1to2[7][2] = -4.91433121355282;
   fWeightMatrix1to2[8][2] = 2.50229106948174;
   fWeightMatrix1to2[9][2] = 2.73894861040968;
   fWeightMatrix1to2[0][3] = 2.95443452119157;
   fWeightMatrix1to2[1][3] = 2.24749614555971;
   fWeightMatrix1to2[2][3] = 0.230702245947875;
   fWeightMatrix1to2[3][3] = -1.31491877332184;
   fWeightMatrix1to2[4][3] = -8.55645967778483;
   fWeightMatrix1to2[5][3] = 2.6282073133583;
   fWeightMatrix1to2[6][3] = -2.49210309947709;
   fWeightMatrix1to2[7][3] = -1.46176299336088;
   fWeightMatrix1to2[8][3] = 5.44610040837715;
   fWeightMatrix1to2[9][3] = 1.56245529233798;
   fWeightMatrix1to2[0][4] = 5.75324047379092;
   fWeightMatrix1to2[1][4] = 1.18939282354511;
   fWeightMatrix1to2[2][4] = 0.689246136624939;
   fWeightMatrix1to2[3][4] = -0.757461818356679;
   fWeightMatrix1to2[4][4] = 4.95635896327662;
   fWeightMatrix1to2[5][4] = 4.88843575893434;
   fWeightMatrix1to2[6][4] = 0.406634824425034;
   fWeightMatrix1to2[7][4] = -7.85656207764124;
   fWeightMatrix1to2[8][4] = -2.8028561505468;
   fWeightMatrix1to2[9][4] = 5.31250622314699;
   fWeightMatrix1to2[0][5] = 2.01142873514342;
   fWeightMatrix1to2[1][5] = -5.35960897887467;
   fWeightMatrix1to2[2][5] = 0.76376379621268;
   fWeightMatrix1to2[3][5] = -1.21342594518667;
   fWeightMatrix1to2[4][5] = -1.02350430679596;
   fWeightMatrix1to2[5][5] = 6.60993817883295;
   fWeightMatrix1to2[6][5] = -0.741071613943259;
   fWeightMatrix1to2[7][5] = -9.9988948784743;
   fWeightMatrix1to2[8][5] = -6.9283439492338;
   fWeightMatrix1to2[9][5] = 7.45708590057617;
   fWeightMatrix1to2[0][6] = 3.84367670854672;
   fWeightMatrix1to2[1][6] = 2.12819625506798;
   fWeightMatrix1to2[2][6] = -0.492224303549273;
   fWeightMatrix1to2[3][6] = -1.52019702270523;
   fWeightMatrix1to2[4][6] = -2.9630065325535;
   fWeightMatrix1to2[5][6] = 2.8215112455769;
   fWeightMatrix1to2[6][6] = 0.870443091781063;
   fWeightMatrix1to2[7][6] = -2.1485622411487;
   fWeightMatrix1to2[8][6] = 0.590633041100536;
   fWeightMatrix1to2[9][6] = 1.00369935456908;
   fWeightMatrix1to2[0][7] = 4.06685944531756;
   fWeightMatrix1to2[1][7] = -1.90947188676095;
   fWeightMatrix1to2[2][7] = 1.08024634402039;
   fWeightMatrix1to2[3][7] = 1.10324221032059;
   fWeightMatrix1to2[4][7] = 0.458893472377387;
   fWeightMatrix1to2[5][7] = -0.417407443601112;
   fWeightMatrix1to2[6][7] = 0.220662349705505;
   fWeightMatrix1to2[7][7] = 0.778587501246051;
   fWeightMatrix1to2[8][7] = 4.94558222870863;
   fWeightMatrix1to2[9][7] = 3.35730805706155;
   fWeightMatrix1to2[0][8] = -4.00412853806737;
   fWeightMatrix1to2[1][8] = 0.788079781478248;
   fWeightMatrix1to2[2][8] = 2.80173522554726;
   fWeightMatrix1to2[3][8] = 0.895682923460091;
   fWeightMatrix1to2[4][8] = 4.31766758988285;
   fWeightMatrix1to2[5][8] = 0.947512108132843;
   fWeightMatrix1to2[6][8] = 0.534032468718839;
   fWeightMatrix1to2[7][8] = -9.70796509457321;
   fWeightMatrix1to2[8][8] = -5.7289021315532;
   fWeightMatrix1to2[9][8] = 6.44937391495556;
   fWeightMatrix1to2[0][9] = -3.07933260373912;
   fWeightMatrix1to2[1][9] = 0.39851602846636;
   fWeightMatrix1to2[2][9] = 1.06617673698216;
   fWeightMatrix1to2[3][9] = -1.02401085131376;
   fWeightMatrix1to2[4][9] = 0.196906364737258;
   fWeightMatrix1to2[5][9] = -3.88598145660047;
   fWeightMatrix1to2[6][9] = 1.15151017852562;
   fWeightMatrix1to2[7][9] = -6.52290138363135;
   fWeightMatrix1to2[8][9] = 4.16478169085971;
   fWeightMatrix1to2[9][9] = 1.60757480571644;
   fWeightMatrix1to2[0][10] = 3.58460421510308;
   fWeightMatrix1to2[1][10] = 0.434737090710349;
   fWeightMatrix1to2[2][10] = 2.82473095058424;
   fWeightMatrix1to2[3][10] = -2.8851894359977;
   fWeightMatrix1to2[4][10] = -0.518137064296275;
   fWeightMatrix1to2[5][10] = 0.458942647273876;
   fWeightMatrix1to2[6][10] = -1.41543396508784;
   fWeightMatrix1to2[7][10] = -2.71060696626481;
   fWeightMatrix1to2[8][10] = -0.577774017873812;
   fWeightMatrix1to2[9][10] = 1.36754046657468;
   fWeightMatrix1to2[0][11] = -4.47807272391203;
   fWeightMatrix1to2[1][11] = -3.2361572931315;
   fWeightMatrix1to2[2][11] = -3.27088250460992;
   fWeightMatrix1to2[3][11] = 1.27332373858549;
   fWeightMatrix1to2[4][11] = 0.373675828845512;
   fWeightMatrix1to2[5][11] = -1.82470223396956;
   fWeightMatrix1to2[6][11] = 1.68165724712649;
   fWeightMatrix1to2[7][11] = 0.557499770098272;
   fWeightMatrix1to2[8][11] = -1.16578544585943;
   fWeightMatrix1to2[9][11] = -2.49464449153236;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.33426599085626;
   fWeightMatrix2to3[0][1] = -0.5940027731748;
   fWeightMatrix2to3[0][2] = 0.781205382021431;
   fWeightMatrix2to3[0][3] = 0.836693273215091;
   fWeightMatrix2to3[0][4] = 0.555915503510961;
   fWeightMatrix2to3[0][5] = -0.121253097396722;
   fWeightMatrix2to3[0][6] = -0.989104767259433;
   fWeightMatrix2to3[0][7] = -0.219678484654049;
   fWeightMatrix2to3[0][8] = -0.327654137736075;
   fWeightMatrix2to3[0][9] = -0.364271068533591;
   fWeightMatrix2to3[0][10] = 0.381957424938698;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0329739265144;
   fMax_1[0][0] = 0.999999880791;
   fMin_1[1][0] = 0.156364113092;
   fMax_1[1][0] = 0.999995648861;
   fMin_1[2][0] = 0.0329739265144;
   fMax_1[2][0] = 0.999999880791;
   fMin_1[0][1] = 0.00723528303206;
   fMax_1[0][1] = 0.998612701893;
   fMin_1[1][1] = 0.0544663891196;
   fMax_1[1][1] = 0.996110737324;
   fMin_1[2][1] = 0.00723528303206;
   fMax_1[2][1] = 0.998612701893;
   fMin_1[0][2] = 0.00730751501396;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = 0.061850823462;
   fMax_1[1][2] = 0.999988496304;
   fMin_1[2][2] = 0.00730751501396;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = 0.00363541697152;
   fMax_1[0][3] = 0.996129393578;
   fMin_1[1][3] = 0.0127544533461;
   fMax_1[1][3] = 0.970664560795;
   fMin_1[2][3] = 0.00363541697152;
   fMax_1[2][3] = 0.996129393578;
   fMin_1[0][4] = 4.74463449791e-05;
   fMax_1[0][4] = 3.14159250259;
   fMin_1[1][4] = 0.0034523003269;
   fMax_1[1][4] = 3.14159107208;
   fMin_1[2][4] = 4.74463449791e-05;
   fMax_1[2][4] = 3.14159250259;
   fMin_1[0][5] = 4.78156437111e-07;
   fMax_1[0][5] = 3.1415913105;
   fMin_1[1][5] = 9.47753214859e-05;
   fMax_1[1][5] = 3.1414539814;
   fMin_1[2][5] = 4.78156437111e-07;
   fMax_1[2][5] = 3.1415913105;
   fMin_1[0][6] = 4.39227072491e-08;
   fMax_1[0][6] = 0.911039710045;
   fMin_1[1][6] = 1.84608052223e-06;
   fMax_1[1][6] = 0.653091073036;
   fMin_1[2][6] = 4.39227072491e-08;
   fMax_1[2][6] = 0.911039710045;
   fMin_1[0][7] = 0.000330226437654;
   fMax_1[0][7] = 0.930747449398;
   fMin_1[1][7] = 0.00129859871231;
   fMax_1[1][7] = 0.733344316483;
   fMin_1[2][7] = 0.000330226437654;
   fMax_1[2][7] = 0.930747449398;
   fMin_1[0][8] = 0.226021185517;
   fMax_1[0][8] = 0.996123611927;
   fMin_1[1][8] = 0.270131677389;
   fMax_1[1][8] = 0.968838214874;
   fMin_1[2][8] = 0.226021185517;
   fMax_1[2][8] = 0.996123611927;
   fMin_1[0][9] = 0.00305365934037;
   fMax_1[0][9] = 0.583633124828;
   fMin_1[1][9] = 0.0112363165244;
   fMax_1[1][9] = 0.578887939453;
   fMin_1[2][9] = 0.00305365934037;
   fMax_1[2][9] = 0.583633124828;
   fMin_1[0][10] = 0.0137960426509;
   fMax_1[0][10] = 3.13912081718;
   fMin_1[1][10] = 0.0577100999653;
   fMax_1[1][10] = 3.08388829231;
   fMin_1[2][10] = 0.0137960426509;
   fMax_1[2][10] = 3.13912081718;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
